services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: trackride
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  backend:
    image: maven:3.9.6-eclipse-temurin-21
    container_name: track-ride-dev
    working_dir: /app
    volumes:
      - .:/app
    command: mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Dspring.devtools.restart.enabled=true"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/trackride
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    container_name: track-ride-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
