services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: trackride
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: track-ride-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/trackride
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: trackride

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: track-ride-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
